In [1]:
list = [9,3,2,7,7,1,3,7,8]

def listsum(list):
    total = 0
    i = 0
    while i < len(list):
        total = total + list[i]
        i = i + 1
    return total

totalsum = listsum(list);
print('Sum of List: ', totalsum)

Sum of List:  47


In [2]:
import numpy as np

arr = np.random.randint(100, size=(2,3))
print('array\n', arr)

max_value = np.max(arr)
print('Largest value in array\n',max_value)

array
 [[76  3 17]
 [26 47 46]]
Largest value in array
 76


In [3]:
#right rotation
import numpy as np

array1 = np.array([7, 8, 3, 1,5,3, 5, 6])
array2 = np.roll(array1, 2) 
print(array2)


[5 6 7 8 3 1 5 3]


In [15]:
#left rotation
import numpy as np

myarray = np.array([1, 2, 3, 4, 5, 6])

newarray =np.roll(myarray, -2) #rotate left
print(newarray)

[3 4 5 6 1 2]


In [55]:
def splitArr(arr, n, k):
        for i in range(0, k):
                x = arr[0]
                for j in range(0, n-1):
                        arr[j] = arr[j + 1]

                arr[n-1] = x
            
arr = [1,2,3,4,5,6,7,8,9,10,11,12]
n = len(arr)
position = 3

splitArr(arr, n, position)
  
for i in range(0, n):
        print(arr[i], end = ' ')









4 5 6 7 8 9 10 11 12 1 2 3 

In [4]:
n = int(input("Enter the lenth of your list : "))
lst = []

for i in range(n):
    lst.append(int(input()))
print("The List is ",lst)

if all((lst[i] <= lst[i+1] for i in range(n-1)) or (lst[i] >= lst[i+1] for i in range(n-1))):
    print("Monotonic")
else:
    print("Not Monotonic")

Enter the lenth of your list : 9
2
7
4
5
7
9
9
8
7
The List is  [2, 7, 4, 5, 7, 9, 9, 8, 7]
Not Monotonic
